on:
  schedule:
    - cron: '0 10 * * 2'
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install MoonBit
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Install MoonBit on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: selene-core
        run: |
          cd selene-core
          moon update
          moon check --deny-warn
          moon build
      
      - name: selene-canvas on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cd selene-canvas
          sed -E -i 's#("Milky2018/selene": )"[^"]+"#\1{ "path": "../selene-core" }#' moon.mod.json
          moon update
          moon check --deny-warn
          moon build

      - name: selene-canvas on MacOS
        if: ${{ matrix.os == 'macOS' }}
        run: |
          cd selene-canvas
          sed -E -i '' 's#("Milky2018/selene": )"[^"]+"#\1{ "path": "../selene-core" }#' moon.mod.json
          moon update
          moon check --deny-warn
          moon build

      - name: selene-canvas on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd selene-canvas
          (Get-Content moon.mod.json) -replace '("Milky2018/selene": )"[^"]+"', '${1}{ "path": "../selene-core" }' | Set-Content moon.mod.json
          moon update
          moon check --deny-warn
          moon build

      - name: selene-examples
        run: |
          cd examples 
          moon update
          moon check --deny-warn
          moon build
